name: generalfly

services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: 'general-db'
    environment:
      - 'POSTGRES_PASSWORD=superusersecret'
    ports:
      - '5432:5432'
    volumes:
      - './dbData:/var/lib/postgresql/data'
